### ISSUE TITLE
Resume from last read feature

### ISSUE THREAD

**Issue by Decad3nce** [trunks-social/trunks-public#131]
https://trunks.social/status/mstdn.social/@Ronald@mastodon.nl/110190355760170426

https://trunks.social/status/mstdn.social/@Lon@mastodon.nl/110190629964880448

**Comment by Decad3nce** [comment]
This is a large effort - deferring it for now.

**Comment by perler** [comment]
I understand but I think this is a mistake. This is so elemental, the original twitter app has it, on the mastodon side https://tapbots.com/ivory/ has it in perfection, https://tusky.app/ in "good enough" form and I really don't know how people can read their timeline in reverse until the point where they say "ok, I think I have seen this already" ?
