### ISSUE TITLE
Unable to log in to trunks on Android, 

### ISSUE THREAD

**Issue by Clfh47** [trunks-social/trunks-public#146]
Just trying trunks for the first time on Android.
Login screen - > selected my host from drop down list: mastodon.green
Login button disabled. 
Tried checking / unchecking login via Web server - still disabled. 
No other obvious action.
No indication of trunks version number

**Comment by Decad3nce** [comment]
Do you know what version of mastodon that domain is using?

@Clfh47

**Comment by kr428** [comment]
Should be 4.1.2 by now.

**Comment by Decad3nce** [comment]
@Clfh47  Can you check alpha.trunks.social or trunks.social (website) and see if this works for you now?
