### ISSUE TITLE
Instance dropdown menu on login screen is not tappable

### ISSUE THREAD

**Issue by wem1c** [trunks-social/trunks-public#160]
## Description
After typing out the partial name of an instance (eg. social.linux.p) the dropdown narrows down the options to the correct instance (eg. social.linux.pizza), but trying to tap it activates the option behind it (the checkbox asking whether to use the external browser for login or not).

## Device info
**model:** Xiaomi Poco F3
**rom:** MIUI Global 14.0.4

## Video
[imgur](https://imgur.com/a/eJe1JZK)
_(Recorder wasn't set to record taps, I'll re-record if necessary. In the video, I'm tapping all over the dropdown option, under the text input.)_

_edits:_
- _added gif of issue mentioned_
- _added device info_

**Comment by Decad3nce** [comment]
I'll look into this, but I'm wondering if it may be Xiaomi specific.

**Comment by Decad3nce** [comment]
Upgraded the dependency for the next release - please let me know if it resolves the issue when it becomes available.

Leaving this ticket open for now.

**Comment by wem1c** [comment]
Tested it out. Issue persists.

**Comment by fgasta** [comment]
Issue persists on version 1.2.5 OnePlus 3T
