### ISSUE TITLE
Audio media support

### ISSUE THREAD

**Issue by subcalc** [trunks-social/trunks-public#20]
![SmartSelect_20230129_221957](https://user-images.githubusercontent.com/58231219/215356591-81809244-fffa-419a-aae2-42759a322e1c.jpg)
![SmartSelect_20230129_222221_Mastodon](https://user-images.githubusercontent.com/58231219/215356592-6844ca89-9327-4739-a6bb-c5dc4d27b8d1.jpg)

Second screenshot is from official mastodon app
Android and web client the same

**Comment by Decad3nce** [comment]
Yeah, I have the code ready for audio playback, just need to stabilize it. Will track as a feature.

**Comment by tcely** [comment]
Please give a way to copy the media URL from trunks ASAP. I'm perfectly happy to play things in VLC, even after trunks has a player.
