### ISSUE TITLE
Text is blurred in the feed

### ISSUE THREAD

**Issue by justdaj** [trunks-social/trunks-public#204]
When scrolling through a feed (example: Home), some of the posts will have slightly blurred text.  As you move the feed the text becomes sharper.  I've not seen this issue in any other app I use.  

Hopefully you can see it in the attached screen shot.  The first post is not as sharp as the second.

Anyone else seeing this?

![2023-06-12_10-54-24](https://github.com/Decad3nce/trunks-public/assets/5741412/9cde4c30-aa34-45ef-8c91-3af855c7dea0)

Web interface. Windows 11.
Microsoft Edge
Version 114.0.1823.43 (Official build) (64-bit)

**Comment by Decad3nce** [comment]
This should be resolved with the change to web assembly in the recent release. I can't repro it locally myself anymore.

Please reopen if it's still a thing
