### ISSUE TITLE
Error shown on some profile pages.

### ISSUE THREAD

**Issue by Decad3nce** [trunks-social/trunks-public#215]

**Comment by wem1c** [comment]
I was about to open an issue for this problem, but this topic may be referencing the same issue:

![Screenshot_2023-06-18-17-23-40-750_com.decad3nce.trunks.jpg](https://github.com/Decad3nce/trunks-public/assets/8087251/a0b6f7b1-0dcf-4753-82eb-f3652e3ce163)

Opening this person's profile, tapping on `posts` and scrolling down triggers the error at the bottom of the screen to show.

Tapping on `retry` removes the error momentarily, after which it immediately shows up again.

The error will also show up upon opening the profile and tapping on `media`, without needing to even scroll.

The error **won't show**:
- after opening the profile and staying on the `about` tab
- after tapping on `posts`, but not scrolling
- after tapping on `activity` and scrolling

The issue also doesn't happen with all profiles, it would seem.

From my account (@wemic@social.linux.pizza), I could reproduce the issue with:
- @dmitry@file-explorers.club
- @feditips@mstdn.social
- @lynnandtonic@front-end.social

but not with:
- @selea@social.linux.pizza
- @fsfe@mastodon.social
- @simon@simonwillison.net

**Comment by Decad3nce** [comment]
Thanks for the details on this, it'll definitely help in fixing it
