### ISSUE TITLE
Comments button timing bug

### ISSUE THREAD

**Issue by wem1c** [trunks-social/trunks-public#222]
Wasn't sure how best to title this issue.. 😅

## Issue
After boosting a post, if you tap on the "comments" button it will seemingly lead to the original post, but there won't be any comments loaded and the top of the ui will say that the author is your own account, rather than the op.

This behavior will persist for about 10 seconds, after which it will be restored to normal/expected.

## Proof
[*screenrec*](https://imgur.com/a/INlaHxI)

## Sys info
- Android 13
- MIUI Global 14.0.7
- Trunks ver. 1.2.5:130

**Comment by Decad3nce** [comment]
I've been running into myself - it's a problem with boosts and some in memory caching issues.
