### ISSUE TITLE
Add option to set all reply visibility.

### ISSUE THREAD

**Issue by Decad3nce** [trunks-social/trunks-public#225]
https://trunks.social/status/mstdn.social/@TheDefiant604@canada.masto.host/110648680022282387

**Comment by tcely** [comment]
This is the "replies default to unlisted" feature that FediLab already has.

I don't even think this needs to be an option. It should just be the way it works. It makes no sense to start a reply as public visibility, especially when my account setting for default visibility is not public.

Every public post should be a choice the user made, not something the app assumed.
