### ISSUE TITLE
[Android][Improvements] Better app launching experience

### ISSUE THREAD

**Issue by cccClyde** [trunks-social/trunks-public#231]
### Description

For a better user experience and also better visuals, please consider Android 12's splash screen implementation and allowing offline app launch 

### Repro Steps

- Force close Trunks for a cold start
- Tap the app icon to launch the app

### Expected Results

1. Nice animation transition from app icon to the splash screen logo
2. Entering the app without stucking in the splash screen and waiting

### Actual Results

1. There's a clearly shift from app icon to the loading screen's bigger Trunks icon
2. We can't enter the app if the internet connection is poor, will have to wait for the feed to refresh

### Notes

For the splash screen animation, now that we have adaptive icon and themed icon, it shouldn't be too hard to implement following this guide [here](https://developer.android.com/develop/ui/views/launch/splash-screen).

**Comment by tcely** [comment]
It would be very useful to enter the app to switch accounts or adjust settings even while my main account cannot be reached.

**Comment by Decad3nce** [comment]
I appreciate this - will have to adapt across Android/iOS/Web to make sure it works uniformly.
