### ISSUE TITLE
Startup loading time

### ISSUE THREAD

**Issue by splendidbits** [trunks-social/trunks-public#234]
Another Seattle-based Android dev here. Thanks for the app ~ It's great.

One large-ish barrier-to-entry for me is the cold-start time when opening Trunks. I figure it's doing something network related, but could this be shifted to a in-the-background caching / updating model? 

Thanks again

**Comment by tcely** [comment]
This seems similar to #231.

**Comment by Decad3nce** [comment]
Closing and duping to #231

Thanks for the report.

I do want to improve this - I'm currently verifying credentials on every cold start.
