### ISSUE TITLE
Own account doesn't open

### ISSUE THREAD

**Issue by luca020400** [trunks-social/trunks-public#236]
Trunks > top/right avatar > click @you > nothing loads

![Screenshot_20230723-163045_ASUS_Launcher.jpg](https://github.com/trunks-social/trunks-public/assets/3950785/945f6a05-9730-4b5c-9354-06773e8a2f97)

That's about the whole issue, thanks!

**Comment by Decad3nce** [comment]
Yeah, it's in the beta. I broke it this morning fixing something else 😔
