### ISSUE TITLE
Home feed goes crazy after blocking someone 

### ISSUE THREAD

**Issue by maksimovic** [trunks-social/trunks-public#245]
What happened:
1. Noticed a person in the feed whose toots are not something I'd like to see :)
2. Blocked that person from a toot that was in the home feed
3. Home feed became blank from that toot and up (the rest of the feed below was visible)
4. Did a refresh of the feed, it seemed like I fixed it, but then after scrolling down I've noticed that now there's a white box from the previously blocked person's toot and below.

App reopen then fixed it. Attaching the screenshot of the state of affairs in the step 4.

![Screenshot_2023-07-25-23-53-06-935_com decad3nce trunks](https://github.com/trunks-social/trunks-public/assets/1126226/fd275208-b64f-4f47-bc3d-7b4f172263c5)

**Comment by Decad3nce** [comment]
Is this on the beta? If so, can you turn off notification grouping and try?
