### ISSUE TITLE
[performance] [android] delay when pressing the settings/accounts menu in the upper right corner

### ISSUE THREAD

**Issue by plaidman** [trunks-social/trunks-public#250]
I've noticed everything in the app is very zippy and performant, but when I press the icon in the upper right corner to pull down the settings/accounts menu, there is a noticeable delay. If you are pulling account data (maybe names and avatars?) perhaps you can show the menu first then perform the request to update account data in the background.

**Comment by Decad3nce** [comment]
There's actually no data being pulled - the only thing I can think of is that the layout is being delayed because the size of the avatar isn't known.

I'll check on that.
