### ISSUE TITLE
filtering doesn't appear to work

### ISSUE THREAD

**Issue by markrprior** [trunks-social/trunks-public#254]
I have a filter that looks for keywords that include the hashtag caturday so I shouldn't see images of cats but trunks has other ideas.
![screenshot of trunks 1.2.6:150](https://github.com/trunks-social/trunks-public/assets/6236685/3023d225-4714-4ca6-8e80-de2a61daec4c)

**Comment by Decad3nce** [comment]
From your screenshot it shows that the content was labeled as filtered with your filter title.

I assume in your filter you have it set to 'warn'?

Likewise, I assume you may also have the setting for expand all content warnings enabled?

If so, trunks knew this content was filtered with your label for a warning but then also respected your setting for always expanding?

**Comment by markrprior** [comment]
> From your screenshot it shows that the content was labeled as filtered with your filter title.
> 
> I assume in your filter you have it set to 'warn'?
> 
> Likewise, I assume you may also have the setting for expand all content warnings enabled?
> 
> If so, trunks knew this content was filtered with your label for a warning but then also respected your setting for always expanding?

OK that explains the behaviour I am seeing, it's just not consistent with what the standard web site does, or the other app I use. In particular I wasn't expecting it to treat a filter with warning as a content warning and then cascade to it's configuration. It would seem that trunks can't do what I want, which is I determine what appears with a content warning rather than the publisher.

**Comment by Decad3nce** [comment]
"which is I determine what appears with a content warning rather than the publisher."

This is you determining what has a content warning. You put in your filter that you want posts to have a warning when the content matches the filter.

I don't see anything wrong in the logic here. I just don't want to add two different kinds of warnings - that's added complexity I don't see a point for.

**Comment by markrprior** [comment]
> I don't see anything wrong in the logic here. I just don't want to add two different kinds of warnings - that's added complexity I don't see a point for.

I don't see why you would need two types of warnings, as you have already noted a filter can be either be configured to warn or hide so that shows the user's intent. There seems no point in having the warn filter at all if content warnings are configured off.
