### ISSUE TITLE
Editor UI bugs

### ISSUE THREAD

**Issue by cccClyde** [trunks-social/trunks-public#255]
![Screenshot_20230823_220758.jpg](https://github.com/trunks-social/trunks-public/assets/34314096/9617e133-41bb-4b4e-808b-bf54c3a1d4e7)

1. The "Publish" button should have some margin or padding (idk) to the left
2. There is a blank bar after the keyboard is dismissed

**Comment by Decad3nce** [comment]
Must say this is WAI
