### ISSUE TITLE
Blank screen after doing an oath authentication login

### ISSUE THREAD

**Issue by asarch** [trunks-social/trunks-public#263]
In Android using the latest release:

![Screenshot_20231004-122401](https://github.com/trunks-social/trunks-public/assets/906401/c032b67f-4a62-42db-b5ab-b98654ac2a26)

![Screenshot_20231004-120754](https://github.com/trunks-social/trunks-public/assets/906401/bae03f31-4038-4d4e-8e33-7c9f4aa71595)

**Comment by Decad3nce** [comment]
I'm guessing your using firefox mobile since you have the "external browser option"?

If so, this is a bug with firefox - not the app.
