### ISSUE TITLE
Chronological Sorting is Reversed

### ISSUE THREAD

**Issue by DonSerrot** [trunks-social/trunks-public#266]
Checked with both the new beta Android app and the web version on my PC. Oldest comments are being placed at the bottom instead of the top.

Using a recent post of my own as an example. Standard Mastodon has the comment order as Michael, Byleth, and Sirena. 
https://gamepad.club/@DonSerrot/111196920643819708

Trunks chronological instead goes Sirena, Byleth, and Michael.
https://trunks.social/status/gamepad.club/@DonSerrot/111196920643819708

App version: 1.2.8:158
Android version: 13 (Pixel 4a)

**Comment by Decad3nce** [comment]
Thanks for this!
