### ISSUE TITLE
Moderation Reports appear to break loading of Notifications tab

### ISSUE THREAD

**Issue by rxbrad** [trunks-social/trunks-public#277]
I run a single-user instance.  Ever since I received a Moderation Report on a specific user account, the Notifications tab has been unable to load.  I just get an infinite loading icon.

![image](https://github.com/trunks-social/trunks-public/assets/13750413/ae95bc8f-ef2e-4b2c-956b-71bfadae7092)

Android v1.2.8:161

**Comment by rxbrad** [comment]
Of note, I was still able to receive push notifications while this behavior occurred.  I just could not view the Notifications tab within the trunks app.

After clearing my account's notifications via the Mastodon web interface, the tab populated correctly again.

**Comment by rxbrad** [comment]
Also, the Debug screen for notifications showed no specific errors.

```
Id: true
Keys: true
Subscription: true
Error
```

**Comment by Decad3nce** [comment]
Thanks for the report! I'll look into it.
