### ISSUE TITLE
[Android] When aspect ratio changes while scrolling from last known position the app loses a bunch of posts

### ISSUE THREAD

**Issue by chriskuchin** [trunks-social/trunks-public#281]
When scrolling up from a remembered point if after getting past the last point the phone rotates changing the aspect ratio and then if it changes back it will forget where it was and some of the posts will have disapeared. Last Time I did it reopened saying as was all caught up and nothing more to see but closing and reopening loaded a different set of posts.

Closing and Reopening the app restores some of it but some posts seem completely gone. 

I have seen a similar behavior when I accidentally click into a conversation/thread while scrolling up.

## Feed Settings
Remember Mode

Conversation Grouping in feeds [on]
Context Fetching for grouped conversations in feeds [on]
Always expand poss with content labels [on]
Show link previews [on]
Play gifs automatically [on]
Prefer Single Column Feed[on]

**Comment by Decad3nce** [comment]
I believe I fixed this in the latest 1.2.10 beta update pending rollout.
Let me know when you get a chance.

As for retaining list position, there's a separate bug tracking that.

**Comment by chriskuchin** [comment]
Cool Yeah I noticed yesterday that something seemed better. It jumped ahead in list a bit but didn't seem to completely lose any posts as I was able to get back to post I had been looking at
