### ISSUE TITLE
Some Unicode (?) characters not showing correctly in Android client

### ISSUE THREAD

**Issue by MrThistle** [trunks-social/trunks-public#286]
Some accounts use special characters and they don't render correctly.
Also, when I try to enter "rational numbers like 1/5" they are not showing correctly.
See two attached screenshots.

Phone: Asus Zenfone 8 with offical Android 13 and all latest updates.
Trunks: The latest version 1.2.12:217

Phone primary language is English, secondary Czech, sometimes I change the primary language to Czech (but usually only for a while).
I have seen it also some time ago, so it is not a new bug.
In the message editor, I am trying to write 1 (top index), 1/2, 1/3, ... as available on "1" key in the keyboard when numbers are visible (long press the "1" key).

![Trunsk - Special characters (wrong, small)](https://github.com/trunks-social/trunks-public/assets/25729376/ba7b5d65-1e6b-460d-bedf-84cb906ae8ff)
![Trunsk - Account name (wrong, small)](https://github.com/trunks-social/trunks-public/assets/25729376/1fd894bf-51c7-462b-b030-06af8ba33a66)

**Comment by amayasnep** [comment]
I’m having the same issue with the iOS client. Trunks will display everything correctly upon initial sign in, but shortly thereafter any text that isn’t plain English throws errors. My user profile on Mastodon includes French, Spanish, Greek, Traditional Mandarin Chinese, and some emojis.

Phone: iPhone 12 Pro
OS: iOS 17.3.1 (latest)
Trunks: The latest version 1.2.17

![IMG_0611](https://github.com/trunks-social/trunks-public/assets/163507694/ceb8cd64-ba7f-4eef-96f5-522c517da541)

**Comment by Decad3nce** [comment]
This happens on iOS as well.

I just made a beta build for 1.2.18 that should address this.

It was a combination of encoding issues along with font issues. :(

**Comment by MrThistle** [comment]
Hi, I am sorry but the issue is not resolved yet.
I tried to write all "shifted" characters in numeric keyboard starting with 1, 1/2 up to 1/10
![Screenshot_20240318-200940857_1](https://github.com/trunks-social/trunks-public/assets/25729376/ea7e8101-9d05-4009-bb75-2f28eebf91ef)

**Comment by amayasnep** [comment]
The same issue I showed before persists even now.

**Comment by Decad3nce** [comment]
Seems to be https://github.com/flutter/flutter/issues/115517

**Comment by Decad3nce** [comment]
I may have finally resolved this in the 1.2.21 beta
