### ISSUE TITLE
Portrait-orientation videos get stretched to landscape on fullscreen

### ISSUE THREAD

**Issue by rxbrad** [trunks-social/trunks-public#288]
If a video is filmed in portrait orientation, viewing it in fullscreen distorts & stretches it to landscape orientation.

Example: 
https://www.threads.net/@mosseri/post/C01zMgWp4V-

Android v1.2.12:217

**Comment by MrThistle** [comment]
@Decad3nce Hi, I think it hasn't been fixed yet, at least in  version 1.2.15:235.
