### ISSUE TITLE
Bug: trunks forgets

### ISSUE THREAD

**Issue by nf3xn** [trunks-social/trunks-public#294]
trunks appears to forget user settings. creates multiple sets of permissions.

**Steps to reproduce:**
Visit trunks.social, allow application to connect to your account & login, set up personalized settings, etc. 

It is not necessary to install the app but it makes no difference anyway. 

**What we expect to happen:**
The application should retain the settings, localStorage is removed manually or is it uninstalled. I do not expect logging out to clear the settings, i.e. logging in again should have the same theme and feed settings etc. 

**What happens instead of that:**
The user is presented with login again. All settings are lost even when the user logs in again. The user is presented with a new login even if they have not logged out. 

**Additional notes:**
One serious side effect is that each and every time the user logs in they are presented with application authorization even if there are permissions. Is this a potential security issue since a user might revoke one set of permissions and still have another set?

![image](https://github.com/trunks-social/trunks-public/assets/88434068/92ad4755-c598-423f-8ba6-4183dbca299d)

**Comment by nf3xn** [comment]
I think this is related to browser settings for blocking ads somehow? I currently cannot test this on Firefox Nightly because it simply never logs in. I have removed authorization from the app.

**Comment by Decad3nce** [comment]
This is more than likely related to your browser, browser settings, or a browser extension.

I assume it's blocking the ability of the web app to store any settings.
