### ISSUE TITLE
[Android] "Remember" mode does not remember, jumps to top on app start

### ISSUE THREAD

**Issue by zopieux** [trunks-social/trunks-public#298]
Trunks Android 1.2.16.

To reproduce: 

* ensure settings are on Remember mode
* scroll down a lot into home timeline
* use another app for a while so Android recycles Trunks, or kill it manually (I tested both)
* open Trunks again (it loads from scratch)

Expected behavior:

I'm on the home timeline position I left the app.

Current behavior:

Trunks shows the latest toots.

Am I holding this wrong? What is the point of "remember" mode if not this? Do I need to tap a button to trigger the memory? Thanks for an otherwise great app!

**Comment by Decad3nce** [comment]
If you're using another app it is also likely updating your marker for the home timeline. So this behavior is expected.

This is also why you can use the web version (or any version) of trunks and continue where you left off on mobile.

**Comment by Decad3nce** [comment]
The API is this https://docs.joinmastodon.org/methods/markers/

**Comment by zopieux** [comment]
>If you're using another app it is also likely updating your marker for the home timeline. So this behavior is expected.

I am not using another app though, I simply navigate away for a while (or kill Trunks). I created an app on my instance to be able to get the markers. I'm staying on the same timeline position with Trunks in the foreground, hoping it'd send the marker to the API, but I'm not seeing it happening. `GET`ing the markers returns an empty object.

I can't tell what makes Trunks trigger saving the marker (and I can't inspect the source code). When does that happen, please?

**Comment by zopieux** [comment]
All right, I got Trunks to **load** the timeline position that was saved by a *different* app that I know is storing the marker using the API. However I also confirm I can't get Trunks to **save/update** that marker. Since the source is not available I can't check what triggers the save. A hint or some doc would be welcome, thanks!

**Comment by lepanen** [comment]
I have same kind of problem, but it happens in iOS, iPadOS and Android in similar manner. It doesn't matter if I have remember mode or stay in top -mode, trunks scrolls back where it was when I opened it first time earlier.
At one point I even got it to load old messages over the point where it said that this is where you dropped off.
