### ISSUE TITLE
Request: add support for other LaTeX delimiters, namely \(\) and \[\]

### ISSUE THREAD

**Issue by oantolin** [trunks-social/trunks-public#301]
I'm very happy to see that trunks renders LaTeX formulas (out of curiosity, do you use KaTeX or MathJax?) but unfortunately the delimiters it uses, namely `$$ $$` do not seem to be in common use on Mastodon so the rendering never actually happens for me. The Mastodon instance with the largest number of mathematicians has to be mathstodon.xyz and that instance uses `\(\)` for inline math and `\[\]` for display math. I'd love it if those delimiters were supported in addition to `$$ $$`.

**Comment by Decad3nce** [comment]
![Simulator Screenshot - iPhone 14 Pro - 2024-04-26 at 23 24 00](https://github.com/trunks-social/trunks-public/assets/315745/d8e4ca45-3c60-4369-a3b4-2daef4b55397)

 :)

**Comment by oantolin** [comment]
Great, thanks!
