### ISSUE TITLE
Bug: feed freezes/becomes unresponsive and goes blank periodically

### ISSUE THREAD

**Issue by mbestavros** [trunks-social/trunks-public#302]
I've noticed this bug intermittently for a long while now (several months, at least). Occasionally, I'll encounter a giant gap in my home feed, and the app becomes completely unresponsive to scrolling. The only fix is to use the "Skip to new posts" button, at which point scrolling gets fixed.

Example screencap:

https://github.com/trunks-social/trunks-public/assets/10786787/d9e26449-3a4e-4175-8860-e708c966fe79

After reproducing, I checked my feed on a separate client (Elk) and found the next post that trunks seemed to freeze on: https://elk.zone/www.theverge.com/2024/5/1/24146079/leaked-lego-lunar-rover (that's from a bot that aggregates The Verge's "quickposts" to the Fediverse). Hope that's helpful.

I'm on a Pixel 8 Pro, running the April security update (I've seen it across many Android versions, though), and I'm running Trunks `1.2.22:273`.

**Comment by Decad3nce** [comment]
Thanks for the video and report!

Unfortunately I'm not able to replicate the issue by going to The Verge Flipboard account.

Do you by chance have a link to the offending post? The elk link above doesn't seem to work.

**Comment by mbestavros** [comment]
@Decad3nce Oh shoot, sorry. It's actually not The Verge's Flipboard account that caused the issue. I follow a few `theverge.space` accounts that aggregate their quick posts - this is the account that had the problematic post: `@sean_hollister@theverge.space`

It doesn't look like it's based on Mastodon, but it does use the ActivityPub protocol, so it is visible from Mastodon apps including Trunks. Attempting to get a post link just gives me a Verge link.

**Comment by Decad3nce** [comment]
Thanks, looks like the post has far more than 4 media attachments. I just capped it at max 4.
![Simulator Screenshot - iPhone 15 Pro - 2024-05-05 at 13 27 03](https://github.com/trunks-social/trunks-public/assets/315745/658c3cc2-783f-46a7-aa70-f3e843ea2ea7)
