### ISSUE TITLE
[Feature] Make the toolbar (with the 'Publish' button) sticked to the bottom and fixed at the top of the keyboard

### ISSUE THREAD

**Issue by ivan-antonenko** [trunks-social/trunks-public#307]
While creating a post, the toolbar scrolls along with the written text, and the 'Publish' button is not visible if the text is long.
It is needed to scroll the screen to find the button, which is absolutely inconvenient.
Please make it fixed at the bottom, at the top of the keyboard.

 ![signal-2024-06-13-101326_002](https://github.com/trunks-social/trunks-public/assets/142349290/e8ec7d71-650a-4316-909f-9c18a7156bea)

**Comment by Decad3nce** [comment]
This is only on the beta because of the new thread posting experience.
