### ISSUE TITLE
Post content after triple ticks are not shown

### ISSUE THREAD

**Issue by arshadrr** [trunks-social/trunks-public#309]
Example post: https://mastodon.social/@glyph/112628092787725236

The content of the post that follows the triple ticks (surrounding the code block) does not show in the app.

Screenshot: https://imgur.com/a/SCmMlEe

Thanks for your work on the app :)

**Comment by Decad3nce** [comment]
<img width="642" alt="Screenshot 2024-06-17 at 17 23 43" src="https://github.com/trunks-social/trunks-public/assets/315745/767822cb-8d78-4684-ae9f-acb2c5fac82a">
This is fixed in the beta!
