### ISSUE TITLE
Trunks appears to encode booleans as strings in JSON

### ISSUE THREAD

**Issue by daenney** [trunks-social/trunks-public#310]
Based on an issue that was raised with GoToSocial developers at https://github.com/superseriousbusiness/gotosocial/issues/3010, it seems that Trunks is encoding certain boolean fields as strings when sending JSON.

This works with Mastodon because it seems to type coerce the fields (I think that might be a Ruby on Rails feature). However, GtS doesn't do that and I'm not sure other server implementations do either.

For example, when trying to follow an account using Trunks, the following JSON is sent to `/api/v1/accounts/:id/follow`:

```json
{"reblogs":"true"}
```

We expect this to be `true` in JSON, without the wrapping quotes, since the [Mastodon API defines it as a boolean](https://docs.joinmastodon.org/methods/accounts/#form-data-parameters-2) and JSON has an explicit type for it.

Trunks seems to be the only client we're aware of that triggers this issue.

**Comment by Decad3nce** [comment]
Thanks for the heads up! I've resolved issues with a few API calls relating to this, I'll do a full clean up of type definition as part of an incremental bug fix update.

**Comment by Decad3nce** [comment]
Looks liike this was just the follow button
