### ISSUE TITLE
Images are noticeably lower quality than in other clients

### ISSUE THREAD

**Issue by alexreid** [trunks-social/trunks-public#313]
Images loaded in Trunks are noticeably lower-quality than other clients, even when expanded to be full screen. It's like a low-quality thumbnail is always used instead. 

# Trunks on iOS
![image](https://github.com/user-attachments/assets/9fb79749-554b-4742-af1b-75260ce11f11)

# Ivory on iOS
![image](https://github.com/user-attachments/assets/02587780-c008-4aa1-bcf0-86e8aa50e988)

**Comment by WimDaWinner** [comment]
Am facing the same issue here, on my Android device. Images seem to be lower in resolution than those in other Mastodon clients, such as Moshidon.

**Comment by Decad3nce** [comment]
Finally figured this out, should be resolved in the next beta/productio release.
