### ISSUE TITLE
Hashtag search doesn't work

### ISSUE THREAD

**Issue by ratcatcher** [trunks-social/trunks-public#320]
If I click on a hashtag - in a post, from Trending or as the result of a search - presumably it's meant to open a screen with the hashtag at the top and a list of recent posts that use that hashtag.

It doesn't.  I just get a screen with the hashtag at the top and nothing else.

This is on my tablet.  On my phone, logged into the same account, this works as expected.  So it is soecific to Trunks running on the tablet.  Tablet is running Android 11, phone Android 14, in case that's relevant.

**Comment by ratcatcher** [comment]
OK, on further investigation, this problem only occurs when the tablet is in portrait mode.  If I rotate it to landscape orientation, all of the missing information appears.

**Comment by Decad3nce** [comment]
Unfortunately I'm unable to reproduce this. Do you have more details about what device this is, maybe what size or DPI the tablet is?
![Uploading Screenshot 2024-11-28 at 08.31.36.png…]()

**Comment by ratcatcher** [comment]
I've attached screenshots of what I see when I click on a hashtag in portrait and landscape modes.  For me a lot of functionality is broken in portrait mode on the tablet, compared to portrait mode on my phone, which is fine.

Android 11
10" screen
1200x1920
![Screenshot_20241128-165146](https://github.com/user-attachments/assets/bdaa8d8c-f2a5-497c-824f-e83771b9713d)
![Screenshot_20241128-164437](https://github.com/user-attachments/assets/c15b47bc-9602-49bf-b88e-65ee54bf52e4)

**Comment by Decad3nce** [comment]
Thanks for the notes! I found the culprit, one of the dependencies updated and changed a behavior.
