### ISSUE TITLE
Favourite language locales for those who switch 

### ISSUE THREAD

**Issue by metamoof** [trunks-social/trunks-public#76]
I’m a polyglot, and post in all my languages. The locale menu is too huge for easy language switching.

I’m only ever going to post in English (UK), Spanish (Spain), French (France) and Catalan. There should be a way for me to easily switch between those languages without me having to scroll the massive list.

Ideally, the client should auto-detect which language I’m using, but I’ll settle for an easy-switch menu

**Comment by Decad3nce** [comment]
Detecting keyboard seems to be a limitation right now: https://github.com/flutter/flutter/issues/25841

However, I can at least promote the most recently used posting languages in the sort order.
